### ISSUE TITLE
Make trusted clients logos 6 columns wide

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/markmagic.com#14]

**Comment by msayenko** [comment]
Is there suppose to be code here for review? Not sure why I got the notification email for this :)

**Comment by yamiko-ninja** [comment]
@msayenko 

I made issues in github to easily check them off as I make the commits and the ability to roll back specific changes if you didn't like them. 

Your getting emails because you are watching the repo. If you unwatch it you will only get emails if I mention you. It's the eye just right of the repo title.
